### ISSUE TITLE
Sending modified keys

### ISSUE THREAD

**Issue by adamschoenemann** [svenlr/swift-map#4]
Coming from Windows where I use Autohotkey extensively, I've been enormously frustrated with the keyboard-mapping options for Linux. Your project is so far the closest to something usable I've found, so thanks for that.

With that in mind, do you think it'd be possible to send modified keys? I'd like to bind Capslock+W to Ctrl+Right (moving one word). It seems like it could be a pretty easy job (e.g. using the state parameter with RedirectKey) but alas I'm not a pythonista or particularly knowledgeable in this domain.

Thanks

**Comment by svenlr** [comment]
Hello, thanks for trying out the project!
Yes, you are right, it should be possible with the state parameter for the XLib functions, I will check if I can add an option to the configuration tomorrow.
Unfortunately, this feature, when implemented, will only work when python-xlib is installed. 
Is that an option for you?

**Comment by adamschoenemann** [comment]
I don't think that should be a problem :) Thanks

**Comment by svenlr** [comment]
What you are suggesting seems to work for me on the branch add-modifiers-option now. I already put Caps+W -> Control+Right in config.json. Please note you have to kill the old process of the program (via system monitor) before starting again.

**Comment by adamschoenemann** [comment]
Excellent. I'll test this out when I get back to my Linux machine later today.

**Comment by adamschoenemann** [comment]
Seems to work! But it'll forget other modifiers held down. E.g. Caps+Shift+W won't select a word.

**Comment by svenlr** [comment]
Ok, I think I fixed that on the branch know. Pressing Caps+Shift+W allowed me to select words.

If you need, you can also change Caps+W or add another shortcut to simulate Shift+Control+Right directly by adding multiple modifiers in the config:
``` json
{
        "key_code": 25,
        "mapped_sequences": {
          "down": [
            {"key": "Right", "modifiers": "Control+Shift"}
          ]
        }
}
```

`Alt` is also a valid modifier.

**Comment by adamschoenemann** [comment]
Nice! It seems to work. Good job pushing this through so fast :)

**Comment by svenlr** [comment]
Glad to hear that it works for you! 

Just a note: I did not merge the `config.json` from the add-modifiers-option branch into master, so, on the master branch it is still the same as before.
I should move configuration to `~/.swift-map/` or something, when I have more time in a few weeks.
