### ISSUE TITLE
Tips for the people that don't know anything about changing config.json

### ISSUE THREAD

**Issue by erkanvatan** [svenlr/swift-map#7]
First of all **THANK YOU** for this project. I really appreciate it. It took me quite a few time to understand underlying principles of config.json. That's why I wanted to share things I learned while trying to make  my changes work.

- Open config.json file with some javascript file editor (provides better view, online ones are okay)

- Use xev command in terminal to get keycodes and keysym.
After you click at the box that pops up, every key you press will be captured and keycodes will appear at the terminal.

- To Find what to write after "mapped_key_label":    ----> find keycode of the key from xev and    search for that code in /usr/share/X11/xkb/keycodes/evdev

- To Find what to write after "mapped_keysym":    ----> find keysym directly from xev

- Terminate mainloop.py process from task manager everytime you change config.json
then reopen it using ./mainloop &

If you want to for example make caps + r  act like a esc key use "mapped_key_label":
If you want to assign symbols like / ( ) =  to keys then use "mapped_keysym": 

Hope this helps.

**Comment by svenlr** [comment]
Thank you for writing this guide, it is true that the configuration is rather unhandy at the moment.. Would you mind If I update the ReadMe with your tips when I have time?

**Comment by erkanvatan** [comment]
Of course you can do it, I would be honored :)
